using Google.Protobuf.Reflection;
using SignalP.Annotations;
using SignalP.Tools.ProtocPlugin.Csharp.Helpers;
using SignalP.Tools.ProtocPlugin.Csharp.Helpers.TypeConverters;
using System.CodeDom.Compiler;
using System.Text;

namespace SignalP.Tools.ProtocPlugin.Csharp.Generators;

internal class ServiceGenerator(PluginOptions options)
{
    private readonly ITypeConverter _typeConverter = options.MessageStyle switch
    {
        PluginOptions.MessageStyles.Json => new JsonTypeConverter(),
        PluginOptions.MessageStyles.MessagePack => new MessagePackTypeConverter(),
        PluginOptions.MessageStyles.Protobuf => new ProtobufTypeConverter(),
        _ => throw new ArgumentOutOfRangeException()
    };

    public string GenerateServices(FileDescriptor file)
    {
        if (file.Services.Count is 0)
        {
            return string.Empty;
        }

        var stringBuilder = new StringBuilder();
        using var textWriter = new StringWriter(stringBuilder);
        using var indentedTextWriter = new IndentedTextWriter(textWriter, " ");

        indentedTextWriter.WriteLine(
            $"""
             // <auto-generated>
             //    Generated by the SignalP protocol buffer compiler plugin. DO NOT EDIT!
             //    source: {file.Name}
             // </auto-generated>
             """
        );

        var fileComments = file.GetFileComments();

        if (fileComments.Count > 0)
        {
            indentedTextWriter.WriteLine("//");
            indentedTextWriter.WriteLine("// Original file comments:");
            fileComments.ForEach(x => indentedTextWriter.WriteLine($"//{x}"));
        }

        indentedTextWriter.WriteLine();
        indentedTextWriter.WriteLine("#region Designer generated code");
        indentedTextWriter.WriteLine();

        indentedTextWriter.WriteLine(
            """
            using Microsoft.AspNetCore.SignalR;
            using System;
            using System.Collections.Generic;
            using System.Threading;
            using System.Threading.Tasks;
            """
        );

        indentedTextWriter.WriteLine();
        var @namespace = !string.IsNullOrWhiteSpace(file.GetOptions()?.CsharpNamespace) ? file.GetOptions()?.CsharpNamespace : file.Package;

        if (!string.IsNullOrWhiteSpace(@namespace))
        {
            indentedTextWriter.WriteLine($"namespace {@namespace} {{");
            indentedTextWriter.Indent();
        }

        foreach (var serviceDescriptor in file.Services)
        {
            _generateService(indentedTextWriter, serviceDescriptor);
        }

        if (!string.IsNullOrWhiteSpace(@namespace))
        {
            indentedTextWriter.Outdent();
            indentedTextWriter.WriteLine("}");
        }

        indentedTextWriter.WriteLine();
        indentedTextWriter.WriteLine("#endregion");

        return stringBuilder.ToString();
    }

    private static bool _generateDocCommentBody(IndentedTextWriter writer, string? leadingComments, string? trailingComments)
    {
        var comments = !string.IsNullOrWhiteSpace(leadingComments) ? leadingComments : trailingComments;

        if (string.IsNullOrWhiteSpace(comments))
        {
            return false;
        }

        var lines = comments.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&rt;").Split('\n');

        writer.WriteLine("/// <summary>");
        var lastWasEmpty = false;

        foreach (var line in lines)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                lastWasEmpty = true;
            }
            else
            {
                if (lastWasEmpty)
                {
                    writer.WriteLine();
                }

                lastWasEmpty = false;

                writer.WriteLine($"///{line.Replace("/", "&#x2F;")}");
            }
        }

        writer.WriteLine("/// </summary>");

        return true;
    }

    private static bool _generateDocCommentBody<T>(IndentedTextWriter writer, T descriptor)
        where T: DescriptorBase
    {
        return _generateDocCommentBody(writer, descriptor.Declaration.LeadingComments, descriptor.Declaration.TrailingComments);
    }

    private static void _generateDocCommentServerMethod(IndentedTextWriter writer, MethodDescriptor methodDescriptor)
    {
        if (!_generateDocCommentBody(writer, methodDescriptor))
        {
            return;
        }

        writer.WriteLine(
            methodDescriptor.IsClientStreaming
                ? """/// <param name="requestStream">Used for reading requests from the client</param>"""
                : """/// <param name="request">The request received from the client</param>"""
        );

        writer.WriteLine(
            methodDescriptor.IsServerStreaming
                ? "/// <returns>The stream, sanded to client</returns>"
                : "/// <returns>The response to send back to the client (wrapped by a task).</returns>"
        );
    }

    private static void _generateDocCommentClientMethod(IndentedTextWriter writer, MethodDescriptor methodDescriptor)
    {
        if (!_generateDocCommentBody(writer, methodDescriptor))
        {
            return;
        }

        writer.WriteLine("""/// <param name="parameter">The parameter, sanded to client</param>""");
        writer.WriteLine("/// <returns>>A task indicating completion of the call</returns>");
    }

    private static string _getServiceClassName(ServiceDescriptor descriptor)
    {
        return descriptor.Name;
    }

    private static string _getClientClassName(ServiceDescriptor descriptor)
    {
        return $"{descriptor.Name}ClientBase";
    }

    private static string _getServerInterfaceName(ServiceDescriptor descriptor)
    {
        return $"I{descriptor.Name}HubBase";
    }

    private static string _getServerClassName(ServiceDescriptor descriptor)
    {
        return $"{descriptor.Name}Hub";
    }

    private void _generateServiceClass(IndentedTextWriter writer, ServiceDescriptor serviceDescriptor)
    {
        writer.WriteLine(
            $"/// <summary>Base class for server-side implementations of {_getServiceClassName(serviceDescriptor)}</summary>"
        );

        writer.WriteObsoleteAttribute(serviceDescriptor.GetOptions()?.Deprecated ?? false);

        writer.WriteLine($"public abstract class {_getServerClassName(serviceDescriptor)}: Hub<{_getServerInterfaceName(serviceDescriptor)}>");
        writer.WriteLine("{");
        writer.Indent();

        foreach (var serviceDescriptorMethod in serviceDescriptor.Methods.Where(
                     x => (x.GetOptions().GetExtension(AnnotationsExtensions.Implementation)?.Side ?? Implementation.Types.Side.Server)
                          == Implementation.Types.Side.Server
                 ))
        {
            _generateDocCommentServerMethod(writer, serviceDescriptorMethod);
            writer.WriteObsoleteAttribute(serviceDescriptorMethod.GetOptions()?.Deprecated ?? false);
            writer.WriteGeneratedCodeAttribute();

            var returnType = _getServerMethodReturnType(serviceDescriptorMethod);
            var parameterType = _getServerMethodParameterType(serviceDescriptorMethod);

            writer.WriteLine(
                $"""
                 public virtual {returnType} {serviceDescriptorMethod.Name}({(!string.IsNullOrWhiteSpace(parameterType) ? $"{parameterType} {(serviceDescriptorMethod.IsClientStreaming ? "requestStream" : "request")}, " : string.Empty)}CancellationToken cancellationToken = default)
                 """
            );

            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine("throw new NotImplementedException();");
            writer.Outdent();
            writer.WriteLine("}");
            writer.WriteLine();
        }

        writer.Outdent();
        writer.WriteLine("}");
        writer.WriteLine();
    }

    private string _getServerMethodReturnType(
        MethodDescriptor methodDescriptor
    )
    {
        var streamStyle = methodDescriptor.GetOptions().GetExtension(AnnotationsExtensions.Implementation)?.Streaming?.ServerToClient
                          ?? Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable;

        var type = _typeConverter.GetTypeName(methodDescriptor.OutputType);

        return methodDescriptor.IsServerStreaming switch
        {
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable
                => $"IAsyncEnumerable<{type}>",
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.Channel
                => $"global::System.Threading.Channels.ChannelReader<{type}>",
            false when string.IsNullOrWhiteSpace(type) => "Task",
            false when !string.IsNullOrWhiteSpace(type) => $"Task<{type}>",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private string? _getServerMethodParameterType(
        MethodDescriptor methodDescriptor
    )
    {
        var streamStyle = methodDescriptor.GetOptions().GetExtension(AnnotationsExtensions.Implementation)?.Streaming?.ClientToServer
                          ?? Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable;

        var type = _typeConverter.GetTypeName(methodDescriptor.InputType);

        return methodDescriptor.IsServerStreaming switch
        {
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable
                => $"IAsyncEnumerable<{type}>",
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.Channel
                => $"Task<global::System.Threading.Channels.ChannelWriter<{type}>>",
            false when string.IsNullOrWhiteSpace(type) => null,
            false when !string.IsNullOrWhiteSpace(type) => type,
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private string _getClientMethodReturnType(MethodDescriptor methodDescriptor)
    {
        var streamStyle = methodDescriptor.GetOptions().GetExtension(AnnotationsExtensions.Implementation)?.Streaming?.ServerToClient
                          ?? Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable;

        var type = _typeConverter.GetTypeName(methodDescriptor.OutputType);

        return methodDescriptor.IsServerStreaming switch
        {
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable
                => $"IAsyncEnumerable<{type}>",
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.Channel
                => $"Task<global::System.Threading.Channels.ChannelReader<{type}>>",
            false when string.IsNullOrWhiteSpace(type) => "Task",
            false when !string.IsNullOrWhiteSpace(type) => $"Task<{type}>",
            _ => throw new ArgumentOutOfRangeException()
        };
    }

    private string? _getClientMethodParameterType(MethodDescriptor methodDescriptor)
    {
        var streamStyle = methodDescriptor.GetOptions().GetExtension(AnnotationsExtensions.Implementation)?.Streaming?.ClientToServer
                          ?? Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable;

        var type = _typeConverter.GetTypeName(methodDescriptor.InputType);

        return methodDescriptor.IsServerStreaming switch
        {
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.AsyncEnumerable
                => $"IAsyncEnumerable<{type}>",
            true when streamStyle is Implementation.Types.Streaming.Types.StreamingStyle.Channel
                => $"global::System.Threading.Channels.ChannelWriter<{type}>",
            false when string.IsNullOrWhiteSpace(type) => null,
            false when !string.IsNullOrWhiteSpace(type) => type,
            _ => throw new ArgumentOutOfRangeException()
        };
    }


    private void _generateServerInterface(IndentedTextWriter writer, ServiceDescriptor serviceDescriptor)
    {
        writer.WriteLine(
            $$"""
              /// <summary>Interface for client-side implementations of {{_getServiceClassName(serviceDescriptor)}}</summary>
              """
        );

        writer.WriteLine($"public interface {_getServerInterfaceName(serviceDescriptor)}");
        writer.WriteLine("{");
        writer.Indent();

        var clientMethods = serviceDescriptor
            .Methods
            .Where(x => x.GetOptions()?.GetExtension(AnnotationsExtensions.Implementation)?.Side == Implementation.Types.Side.Client)
            .ToList();

        foreach (var methodDescriptor in clientMethods)
        {
            _generateDocCommentClientMethod(writer, methodDescriptor);
            writer.WriteObsoleteAttribute(methodDescriptor.GetOptions()?.Deprecated ?? false);
            writer.WriteGeneratedCodeAttribute();
            writer.WriteLine($"Task {methodDescriptor.Name}({_getServerMethodParameterType(methodDescriptor)} parameter);");
        }

        writer.Outdent();
        writer.WriteLine("}");
    }

    private void _generateClientClass(IndentedTextWriter writer, ServiceDescriptor serviceDescriptor)
    {
        writer.WriteLine(
            $$"""
              /// <summary>Base class for client implementations of {{_getServiceClassName(serviceDescriptor)}}</summary>
              """
        );

        writer.WriteLine($"public abstract class {_getClientClassName(serviceDescriptor)}: IAsyncDisposable");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("public global::Microsoft.AspNetCore.SignalR.Client.HubConnection Connection { get; private set; }");

        writer.WriteLine(
            "private readonly IList<IDisposable> _handlers = new List<IDisposable>();"
        );

        writer.WriteLine();
        writer.WriteLine($"public {_getClientClassName(serviceDescriptor)}(global::Microsoft.AspNetCore.SignalR.Client.HubConnection connection)");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("if (connection == null) throw new ArgumentNullException(nameof(connection));");
        writer.WriteLine("Connection = connection;");

        var clientMethods = serviceDescriptor
            .Methods.Where(
                x => x.GetOptions()?.GetExtension(AnnotationsExtensions.Implementation)?.Side == Implementation.Types.Side.Client
            )
            .ToList();

        foreach (var methodDescriptor in clientMethods)
        {
            var parameterType = _getClientMethodParameterType(methodDescriptor);
            var hasMethodParameter = !string.IsNullOrWhiteSpace(parameterType);

            writer.WriteLine();
            writer.WriteLine("_handlers.Add(");
            writer.Indent();
            writer.WriteLine("global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions");
            writer.Indent();
            writer.WriteLine($".On{(hasMethodParameter ? $"<{parameterType}>" : string.Empty)}(");
            writer.Indent();
            writer.WriteLine("Connection,");
            writer.WriteLine($"\"{methodDescriptor.Name}\",");
            writer.WriteLine($"({(hasMethodParameter ? "x" : string.Empty)}) => {methodDescriptor.Name}({(hasMethodParameter ? "x" : string.Empty)})");
            writer.Outdent();
            writer.WriteLine(")");
            writer.Outdent();
            writer.WriteLine(");");
            writer.Outdent();
        }

        writer.Outdent();
        writer.WriteLine("}");
        writer.WriteLine();


        var serverMethods = serviceDescriptor
            .Methods
            .Where(
                x => (x.GetOptions()?.GetExtension(AnnotationsExtensions.Implementation)?.Side ?? Implementation.Types.Side.Server) == Implementation.Types.Side.Server
            )
            .ToList();

        foreach (var methodDescriptor in serverMethods)
        {
            var returnType = _getClientMethodReturnType(methodDescriptor);
            var parameterType = _getClientMethodParameterType(methodDescriptor);

            writer.WriteLine(
                $"public {returnType} {methodDescriptor.Name}({(string.IsNullOrWhiteSpace(parameterType) ? string.Empty : $"{parameterType} parameter")})"
            );

            writer.WriteLine("{");
            writer.Indent();

            var methodCall = returnType.Equals("Task") ? "InvokeAsync" :
                !returnType.StartsWith("Task<") ? $"InvokeAsync<{returnType}>" : $"InvokeAsync<{returnType.Replace("Task<", string.Empty)[..^1]}>";

            writer.WriteLine(
                $"""
                 return global::Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.{methodCall}(Connection, "{methodDescriptor.Name}"{(_getClientMethodParameterType(methodDescriptor) is not null ? ", parameter" : string.Empty)});
                 """
            );

            writer.Outdent();
            writer.WriteLine("}");
            writer.WriteLine();
        }

        foreach (var methodDescriptor in clientMethods)
        {
            var parameterType = _getClientMethodParameterType(methodDescriptor);

            writer.WriteLine(
                $"protected abstract Task {methodDescriptor.Name}({(string.IsNullOrWhiteSpace(parameterType) ? string.Empty : $"{parameterType} parameter")});"
            );

            writer.WriteLine();
        }

        writer.WriteLine("public ValueTask DisposeAsync()");
        writer.WriteLine("{");
        writer.Indent();
        writer.WriteLine("foreach (var handler in _handlers) handler.Dispose();");
        writer.WriteLine("return Connection.DisposeAsync();");
        writer.Outdent();
        writer.WriteLine("}");

        writer.Outdent();
        writer.WriteLine("}");
    }

    private void _generateService(IndentedTextWriter writer, ServiceDescriptor serviceDescriptor)
    {
        _generateDocCommentBody(writer, serviceDescriptor);
        writer.WriteObsoleteAttribute(serviceDescriptor.GetOptions()?.Deprecated ?? false);
        writer.WriteLine($"{(options.InternalAccess ? "internal" : "public")} static class {_getServiceClassName(serviceDescriptor)}");
        writer.WriteLine("{");
        writer.Indent();

        if (options.Generate.HasFlag(PluginOptions.GeneratedSide.Server))
        {
            _generateServiceClass(writer, serviceDescriptor);
            _generateServerInterface(writer, serviceDescriptor);
            writer.WriteLine();
        }

        if (options.Generate.HasFlag(PluginOptions.GeneratedSide.Client))
        {
            _generateClientClass(writer, serviceDescriptor);
        }

        writer.Outdent();
        writer.WriteLine("}");
    }
}