using Google.Protobuf.Reflection;
using SignalP.Tools.ProtocPlugin.Csharp.Helpers;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;

namespace SignalP.Tools.ProtocPlugin.Csharp.Generators.Models;

internal class MessagePackModelGenerator(PluginOptions options)
{
    public string GenerateModels(FileDescriptor file)
    {
        if (file.MessageTypes.Count is 0)
        {
            return string.Empty;
        }

        var stringBuilder = new StringBuilder();
        using var textWriter = new StringWriter(stringBuilder);
        using var indentedTextWriter = new IndentedTextWriter(textWriter, " ");

        indentedTextWriter.WriteLine(
            $"""
             // <auto-generated>
             //    Generated by the SignalP protocol buffer compiler plugin. DO NOT EDIT!
             //    source: {file.Name}
             // </auto-generated>
             """
        );

        var fileComments = file.GetFileComments();

        if (fileComments.Count > 0)
        {
            indentedTextWriter.WriteLine("//");
            indentedTextWriter.WriteLine("// Original file comments:");
            fileComments.ForEach(x => indentedTextWriter.WriteLine($"//{x}"));
        }

        indentedTextWriter.WriteLine();

        indentedTextWriter.WriteLine("using MessagePack;");

        indentedTextWriter.WriteLine();

        var hasNamespace = file.TryGetNamespace(out var @namespace);

        if (hasNamespace)
        {
            indentedTextWriter.WriteLine($"namespace {@namespace} {{");
            indentedTextWriter.Indent();
        }

        indentedTextWriter.WriteLine("#region Messages");
        indentedTextWriter.WriteLine();

        foreach (var fileMessageType in file.MessageTypes)
        {
            _generateMessage(indentedTextWriter, fileMessageType);
        }

        indentedTextWriter.WriteLine();
        indentedTextWriter.WriteLine("#endregion");

        indentedTextWriter.WriteLine();
        indentedTextWriter.WriteLine("#region Enums");
        indentedTextWriter.WriteLine();

        foreach (var fileEnumType in file.EnumTypes)
        {
            _generateEnum(indentedTextWriter, fileEnumType);
            indentedTextWriter.WriteLine();
        }

        indentedTextWriter.WriteLine("#endregion");
        indentedTextWriter.WriteLine();

        if (hasNamespace)
        {
            indentedTextWriter.Outdent();
            indentedTextWriter.WriteLine("}");
        }

        return stringBuilder.ToString();
    }

    private void _generateEnum(IndentedTextWriter writer, EnumDescriptor enumDescriptor)
    {
        writer.WriteObsoleteAttribute(enumDescriptor.GetOptions()?.Deprecated ?? false);
        writer.WriteLine($"{(options.InternalAccess ? "internal" : "public")} enum {enumDescriptor.Name}");
        writer.WriteLine("{");
        writer.Indent();

        foreach (var enumValueDescriptor in enumDescriptor.Values)
        {
            writer.WriteLine($"{_toPascalCase(enumValueDescriptor.Name)} = {enumValueDescriptor.Number},");
        }

        writer.Outdent();
        writer.WriteLine("}");
    }

    private void _generateMessage(IndentedTextWriter writer, MessageDescriptor messageDescriptor)
    {
        writer.WriteLine("[MessagePackObject]");
        writer.WriteObsoleteAttribute(messageDescriptor.GetOptions()?.Deprecated ?? false);
        writer.WriteLine($"{(options.InternalAccess ? "internal" : "public")} class {messageDescriptor.Name}");
        writer.WriteLine("{");
        writer.Indent();

        foreach (var fieldDescriptor in messageDescriptor.Fields.InFieldNumberOrder())
        {
            writer.WriteLine($"[Key({fieldDescriptor.FieldNumber})]");
            writer.WriteObsoleteAttribute(fieldDescriptor.GetOptions()?.Deprecated ?? false);
            writer.WriteGeneratedCodeAttribute();
            writer.WriteDebuggerNonUserCodeAttribute();
            writer.Write("public ");

            var type = fieldDescriptor.GetClrTypeName();

            writer.WriteLine(
                $"{type} {_toPascalCase(fieldDescriptor.Name)} {{ get;{(fieldDescriptor.IsRepeated ? string.Empty : " set;")} }}"
            );

            if (fieldDescriptor.IsRepeated)
            {
                writer.Indent();
                writer.WriteLine($"= new {type}();");
                writer.Outdent();
            }

            writer.WriteLine();

            if (fieldDescriptor.ContainingOneof is not { } oneofDescriptor)
            {
                continue;
            }

            writer.WriteLine("[IgnoreMember]");
            writer.WriteGeneratedCodeAttribute();
            writer.WriteDebuggerNonUserCodeAttribute();

            writer.WriteLine(
                $"public bool Has{_toPascalCase(fieldDescriptor.Name)} => "
                + $"{_toPascalCase(oneofDescriptor.Name)}Case == {_toPascalCase(oneofDescriptor.Name)}OneOfCase.{_toPascalCase(fieldDescriptor.Name)};"
            );

            writer.WriteLine();
        }


        foreach (var oneofDescriptor in messageDescriptor.Oneofs)
        {
            writer.WriteLine($"public enum {_toPascalCase(oneofDescriptor.Name)}OneOfCase");
            writer.WriteLine("{");
            writer.Indent();
            writer.WriteLine("None = 0,");

            foreach (var fieldDescriptor in oneofDescriptor.Fields)
            {
                writer.WriteLine($"{_toPascalCase(fieldDescriptor.Name)} = {fieldDescriptor.FieldNumber},");
            }

            writer.Outdent();

            writer.WriteLine("}");
            writer.WriteLine();

            writer.WriteLine("[IgnoreMember]");
            writer.WriteGeneratedCodeAttribute();
            writer.WriteDebuggerNonUserCodeAttribute();

            var oneOfName = _toPascalCase(oneofDescriptor.Name);

            writer.WriteLine(
                $"public {oneOfName}OneOfCase {oneOfName}Case {{ get; private set; }}"
            );
        }

        if (messageDescriptor.NestedTypes.Any(x => !x.IsMapEntry) || messageDescriptor.EnumTypes.Any())
        {
            writer.WriteLine();
            writer.WriteGeneratedCodeAttribute();
            writer.WriteLine("public static class Types");
            writer.WriteLine("{");
            writer.Indent();

            foreach (var messageDescriptorNestedType in messageDescriptor.NestedTypes.Where(x => !x.IsMapEntry))
            {
                _generateMessage(writer, messageDescriptorNestedType);
            }

            foreach (var enumDescriptor in messageDescriptor.EnumTypes)
            {
                _generateEnum(writer, enumDescriptor);
            }

            writer.Outdent();
            writer.WriteLine("}");
        }

        writer.Outdent();
        writer.WriteLine("}");
    }

    private static string _toPascalCase(string name)
    {
        var snakeCased = System.Text.Json.JsonNamingPolicy.SnakeCaseLower.ConvertName(name);
        return CultureInfo.InvariantCulture.TextInfo.ToTitleCase(snakeCased.Replace("_", " ")).Replace(" ", string.Empty);
    }
}